### ISSUE TITLE
CClient extended API implementation

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/entangled#532]
This issue logs the implementing status of extended APIs. 

- [x] iota_client_broadcast_bundle (#238)
- [x] iota_client_get_account_data (#239)
- [x] iota_client_get_bundle (#240) 
- [x] iota_client_get_latest_inclusion (#242) 
- [x] iota_client_get_new_address (#243) 
- [x] iota_client_get_transaction_objects (#244) 
- [x] iota_client_find_transaction_objects (#245)
- [x] iota_client_get_inputs (#246)
- [x] iota_client_is_promotable (#248)
- [x] iota_client_prepare_transfers (#250) 
- [x] iota_client_promote_transaction (#251) 
- [x] iota_client_replay_bundle (#252)
- [x] iota_client_store_and_broadcast (#253)
- [x] iota_client_traverse_bundle (#254) 
- [x] iota_client_send_trytes (#255)
- [x] iota_client_send_transfer (#256)
